### ISSUE TITLE
마커 커스텀 (Layout)

### ISSUE THREAD

**Issue by ro0opf** [boostcampth/boostcamp3_D#170]
### You want to:

* [ ] report a *bug*
* [x] request a *feature*
* [ ] request an update to the documentation
* [ ] requeset a code change that improves performance
* [ ] request other

### Current behaviour

*What is actually happening?*

### Expected behaviour

*What is expected?*
* 구글 맵에 표시되는 게시글 마커 커스텀하기

**Comment by Zi-Yun** [comment]
duplicate #256
