### ISSUE TITLE
리사이클러뷰 애니메이션 구현

### ISSUE THREAD

**Issue by ro0opf** [boostcampth/boostcamp3_D#188]
### You want to:

* [ ] report a *bug*
* [x] request a *feature*
* [ ] request an update to the documentation
* [ ] requeset a code change that improves performance
* [ ] request other

### Current behaviour

*What is actually happening?*

### Expected behaviour

*What is expected?*
* 리사이클러뷰 아이템 클릭 시 애니메이션 추가

**Comment by Zi-Yun** [comment]
ripple 을 적용해 구현함.
#277 
#275
