### ISSUE TITLE
검색화면에서 검색할 때 mapfragment select 해주기

### ISSUE THREAD

**Issue by ro0opf** [boostcampth/boostcamp3_D#223]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*
* [ ] request an update to the documentation
* [ ] requeset a code change that improves performance
* [ ] request other

### Current behaviour

*What is actually happening?*
* 현재 홈화면에서 검색화면으로 넘어가 검색 시 mapfragment로 넘어가지 않는 버그가 있습니다.

### Expected behaviour

*What is expected?*

**Comment by Zi-Yun** [comment]
#
