### ISSUE TITLE
RxBus 수정 필요.

### ISSUE THREAD

**Issue by Zi-Yun** [boostcampth/boostcamp3_D#243]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*
* [ ] request an update to the documentation
* [ ] requeset a code change that improves performance
* [ ] request other

### Current behaviour
* complete를 호출해버리는 이상한 코드 수정 필요.

### Steps to reproduce (if the current behaviour is a bug)
* subject에 대해 공부하고 수정해야함.

### Expected behaviour
* 지도 검색
* 디테일 이동 부분에서 정상적으로 작동해야함.

**Comment by leeyc09** [comment]
http://reactivex.io/documentation/ko/subject.html

**Comment by Jiyunn** [comment]
#29
